// ============================================================
// PERMISSIONS — CRM Mondial Home
// Format : resource.action[.scope]
// ============================================================

export const PERMISSIONS = {
  // Clients
  CLIENTS_READ: "clients.read",
  CLIENTS_READ_ALL: "clients.read.all",
  CLIENTS_CREATE: "clients.create",
  CLIENTS_UPDATE: "clients.update",
  CLIENTS_DELETE: "clients.delete",
  CLIENTS_EXPORT: "clients.export",
  CLIENTS_IMPORT: "clients.import",

  // Articles
  ARTICLES_READ: "articles.read",
  ARTICLES_CREATE: "articles.create",
  ARTICLES_UPDATE: "articles.update",
  ARTICLES_DELETE: "articles.delete",

  // Ventes
  SALES_READ: "sales.read",
  SALES_READ_ALL: "sales.read.all",
  SALES_CREATE: "sales.create",
  SALES_UPDATE: "sales.update",
  SALES_DELETE: "sales.delete",
  SALES_EXPORT: "sales.export",

  // Campagnes
  CAMPAIGNS_READ: "campaigns.read",
  CAMPAIGNS_CREATE: "campaigns.create",
  CAMPAIGNS_UPDATE: "campaigns.update",
  CAMPAIGNS_DELETE: "campaigns.delete",
  CAMPAIGNS_SEND: "campaigns.send",
  CAMPAIGNS_APPROVE: "campaigns.approve",

  // Segments
  SEGMENTS_READ: "segments.read",
  SEGMENTS_CREATE: "segments.create",
  SEGMENTS_UPDATE: "segments.update",
  SEGMENTS_DELETE: "segments.delete",

  // Automatisations
  AUTOMATIONS_READ: "automations.read",
  AUTOMATIONS_CREATE: "automations.create",
  AUTOMATIONS_UPDATE: "automations.update",
  AUTOMATIONS_DELETE: "automations.delete",
  AUTOMATIONS_ACTIVATE: "automations.activate",

  // Templates
  TEMPLATES_READ: "templates.read",
  TEMPLATES_CREATE: "templates.create",
  TEMPLATES_UPDATE: "templates.update",
  TEMPLATES_DELETE: "templates.delete",

  // Analytics
  ANALYTICS_READ: "analytics.read",
  ANALYTICS_EXPORT: "analytics.export",

  // Admin
  ADMIN_READ: "admin.read",
  ADMIN_USERS_READ: "admin.users.read",
  ADMIN_USERS_CREATE: "admin.users.create",
  ADMIN_USERS_UPDATE: "admin.users.update",
  ADMIN_USERS_DELETE: "admin.users.delete",
  ADMIN_ROLES_READ: "admin.roles.read",
  ADMIN_ROLES_MANAGE: "admin.roles.manage",
  ADMIN_AUDIT_READ: "admin.audit.read",
  ADMIN_SETTINGS_READ: "admin.settings.read",
  ADMIN_SETTINGS_UPDATE: "admin.settings.update",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// ============================================================
// RÔLES SYSTÈME avec permissions par défaut
// ============================================================

export const ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  MANAGER: "manager",
  AGENT: "agent",
  VIEWER: "viewer",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  super_admin: Object.values(PERMISSIONS),

  admin: [
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_READ_ALL,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.CLIENTS_DELETE,
    PERMISSIONS.CLIENTS_EXPORT,
    PERMISSIONS.CLIENTS_IMPORT,
    PERMISSIONS.ARTICLES_READ,
    PERMISSIONS.ARTICLES_CREATE,
    PERMISSIONS.ARTICLES_UPDATE,
    PERMISSIONS.ARTICLES_DELETE,
    PERMISSIONS.SALES_READ,
    PERMISSIONS.SALES_READ_ALL,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_UPDATE,
    PERMISSIONS.SALES_DELETE,
    PERMISSIONS.SALES_EXPORT,
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.CAMPAIGNS_CREATE,
    PERMISSIONS.CAMPAIGNS_UPDATE,
    PERMISSIONS.CAMPAIGNS_DELETE,
    PERMISSIONS.CAMPAIGNS_SEND,
    PERMISSIONS.CAMPAIGNS_APPROVE,
    PERMISSIONS.SEGMENTS_READ,
    PERMISSIONS.SEGMENTS_CREATE,
    PERMISSIONS.SEGMENTS_UPDATE,
    PERMISSIONS.SEGMENTS_DELETE,
    PERMISSIONS.AUTOMATIONS_READ,
    PERMISSIONS.AUTOMATIONS_CREATE,
    PERMISSIONS.AUTOMATIONS_UPDATE,
    PERMISSIONS.AUTOMATIONS_DELETE,
    PERMISSIONS.AUTOMATIONS_ACTIVATE,
    PERMISSIONS.TEMPLATES_READ,
    PERMISSIONS.TEMPLATES_CREATE,
    PERMISSIONS.TEMPLATES_UPDATE,
    PERMISSIONS.TEMPLATES_DELETE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.ADMIN_READ,
    PERMISSIONS.ADMIN_USERS_READ,
    PERMISSIONS.ADMIN_USERS_CREATE,
    PERMISSIONS.ADMIN_AUDIT_READ,
    PERMISSIONS.ADMIN_SETTINGS_READ,
  ],

  manager: [
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_READ_ALL,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.CLIENTS_EXPORT,
    PERMISSIONS.ARTICLES_READ,
    PERMISSIONS.SALES_READ,
    PERMISSIONS.SALES_READ_ALL,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_EXPORT,
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.CAMPAIGNS_CREATE,
    PERMISSIONS.CAMPAIGNS_UPDATE,
    PERMISSIONS.CAMPAIGNS_SEND,
    PERMISSIONS.SEGMENTS_READ,
    PERMISSIONS.SEGMENTS_CREATE,
    PERMISSIONS.AUTOMATIONS_READ,
    PERMISSIONS.TEMPLATES_READ,
    PERMISSIONS.TEMPLATES_CREATE,
    PERMISSIONS.ANALYTICS_READ,
  ],

  agent: [
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.ARTICLES_READ,
    PERMISSIONS.SALES_READ,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.TEMPLATES_READ,
  ],

  viewer: [
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.ARTICLES_READ,
    PERMISSIONS.SALES_READ,
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.ANALYTICS_READ,
  ],
};
